apiVersion: v1
kind: Service
metadata:
  name: detr-worker
  namespace: video-processing
  labels:
    app: detr-worker
spec:
  selector:
    app: detr-worker
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
      protocol: TCP
  clusterIP: None

