apiVersion: v1
kind: ConfigMap
metadata:
  name: detr-worker-config
  namespace: cvcameratracker
data:
  KAFKA_BROKERS: "kafka-cluster:9092"
  KAFKA_FRAME_TASK_TOPIC: "video-frames-tasks"
  KAFKA_DETECTION_RESULT_TOPIC: "detection-results"
  KAFKA_WORKER_GROUP: "detr-worker-group"
  DETR_MODEL: "facebook/detr-resnet-50"
  CONFIDENCE_THRESHOLD: "0.7"
  HF_HOME: "/home/appuser/.hf"
  TRANSFORMERS_CACHE: "/home/appuser/.cache/huggingface/transformers"
  HF_HUB_CACHE: "/home/appuser/.cache/huggingface/hub"

